### ISSUE TITLE
GIF animations of the key features of using the gitterbot

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#103]
I want to make a pretty README file (or an explanation website) about the gitterbot.

we need some simple gif animation captures of the main features as short little GIF animations to add inline to this:

- thanks @dcsan
- about @dcsan
- help js ternary
- find js
- choose a menu option

then I can write up about those features underneath

these animations should be added to the gh-pages branch of the repo, inside the /images/ directory.

http://dcsan.github.io/gitterbot/

**Comment by dcsan** [comment]
update made a basic page here, we just need to add the graphics in
http://dcsan.github.io/gitterbot/

**Comment by dcsan** [comment]
@kirah1314 is this something you could help with?

**Comment by abhisekp** [comment]
I might contribute gif animations of some of the key features.
