### ISSUE TITLE
uptime monitor

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#161]
the bot should respond to an API call somewhere
and then we can have an uptime monitor

**Comment by dcsan** [comment]
if botstatus replied over http (responded to a GET request) that would be fine.

**Comment by SaintPeter** [comment]
So you're talking about just adding a listener on HTTP for "GET" that would respond 200/OK?

**Comment by dcsan** [comment]
yeah
it could also send back the botstatus (version info etc) as later I may add stats like "concurrent users" there or some other info.

**Comment by SaintPeter** [comment]
Well, I've just got it replying "OK" right now.
We can add more stuff later.

**Comment by dcsan** [comment]
awesome! i'll merge + deploy tonite /tmrw
