### ISSUE TITLE
tighten regex on troll

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#168]
We should tighten the regex on this expression

    (^|\s)troll(\s|$)

![skitch](https://cloud.githubusercontent.com/assets/514002/9457223/2b2b9a0c-4a95-11e5-957f-95383c7977b1.png)

cc @QuincyLarson

**Comment by abhisekp** [comment]
@dcsan wouldn't a word break `\b` around the word **troll** be sufficient?
