### ISSUE TITLE
Change "Falsey" to "Falsy" for Camperbot in HelpBonfires Section

### ISSUE THREAD

**Issue by happyconcepts** [dcsan/gitterbot#178]
![falsy2](https://cloud.githubusercontent.com/assets/14145836/9835204/15ff574c-5993-11e5-8d76-8d57e96475b7.jpg)
Camperbot does not return a result for 'bf falsy' yet it works for 'bf falsey' which may be a relic.

**Comment by dcsan** [comment]
this sounds like a perfect opportunity for you to contribute to an open source project! are you ready?

**Comment by happyconcepts** [comment]
I think so, but am i really supposed to "fork" the whole project just to
make this one change? Surely I am missing something? -Ben

**Comment by happyconcepts** [comment]
Is there a suggested spelling convention to go with? I'm thinking a) consistent spelling one way or the other, or better b) add both falsey and falsy so that camperbot recognises both input terms.

**Comment by ltegman** [comment]
Looking into moving over all the new bonfire json files from FCC to sync this up with them. Will require creating dashed names from the challenge `type` and `name` properties since `dashedName` has been removed but quite a few parts of the gitterbot bonfire code relies on them.

**Comment by ltegman** [comment]
Submitted a PR for this which accounts for various changes to the format of the JSON. Fixes this bug and just generally syncs gitterbot's bonfires back up with FCC.

**Comment by abhisekp** [comment]
fixed in https://github.com/FreeCodeCamp/camperbot/pull/12
