### ISSUE TITLE
Bot is down in /HelpBonfires - 10/26

### ISSUE THREAD

**Issue by SaintPeter** [dcsan/gitterbot#185]
Bot is down in /HelpBonfires and somewhat flakey in some other channels.  Needs to be kicked.

**Comment by abhisekp** [comment]
@SaintPeter Needs to be kicked??
It's a friendly bot. 

Bot dead since 26th October 2015 :point_right: [October 26, 2015 9:56 PM](https://gitter.im/dcsan/gitterbot?at=562e544b011a22571b236aa7)

**Comment by dcsan** [comment]
we're aware of the problem but not sure if it's the bot or gitter API - those rooms are apparently returning a 404 according to @BerkeleyTrue 

maybe one of you could investigate? try booting up your own bot locally and see if it can join all the rooms OK.

**Comment by BerkeleyTrue** [comment]
Yeah saw that in the logs when I restarted it.

**Comment by BerkeleyTrue** [comment]
It was 4 or 5 total. It seemed to join all the rest fine.

**Comment by abhisekp** [comment]
@evaristoc contacted the gitter guys. They say it was not their fault. :point_right: [October 28, 2015 7:55 PM](https://gitter.im/gitterHQ/gitter?at=5630dace738e06e175f462ab)

**Comment by abhisekp** [comment]
The bot is working fine in all channels but the issue is open till the problem is diagnosed.

**Comment by dcsan** [comment]
so it just started workign again?

On Sat, Oct 31, 2015 at 2:49 PM, Abhisek Pattnaik <notifications@github.com>
wrote:

> The bot is working fine in all channels but the issue is open till the
> problem is diagnosed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dcsan/gitterbot/issues/185#issuecomment-152701277>.
>



-- 
-----------------------------------------------
David 'DC' Collier
  dc@biz.pikkle.com
  skype: d3ntaku
  http://jp.linkedin.com/in/dcsan/
-----------------------------------------------

**Comment by abhisekp** [comment]
@dcsan, **mydigitalself** [reported](https://gitter.im/gitterHQ/gitter?at=5630f2018de446b00919b916) it to @QuincyLarson and probably he did something and now bot works fine in [FreeCodeCamp/HelpBonfires](https://gitter.im/FreeCodeCamp/HelpBonfires) and [dcsan/gitterbot](https://gitter.im/dcsan/gitterbot) rooms.

**Comment by BerkeleyTrue** [comment]
The bot is still down in /helpBasejumps. As stated above, all I did was restart the bot. That is where I saw the 404s.

**Comment by SaintPeter** [comment]
The bot has never worked in /HelpBasejumps - I don't think it is on the
current release's list.

Regards,
Rex Schrader


On Sat, Oct 31, 2015 at 7:46 AM, Berkeley Martinez <notifications@github.com

**Comment by joepurdy** [comment]
https://github.com/FreeCodeCamp/camperbot/pull/6 will resolve this on the new repo
