### ISSUE TITLE
Bot reports api offline

### ISSUE THREAD

**Issue by joepurdy** [dcsan/gitterbot#188]
After FCC did maintenance and migrated DNS the bot is reporting that it cannot access the API for commands like thanks.js that require communicating with the FCC api.

<blockquote class="twitter-tweet" lang="en"><p lang="en" dir="ltr">We&#39;re doing a DNS migration. We may have weird outages for the next hour or so (hopefully not). Thanks for your patience.</p>&mdash; Free Code Camp (@FreeCodeCamp) <a href="https://twitter.com/FreeCodeCamp/status/661099878009843712">November 2, 2015</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

The FCC admins confirmed nothing is changed on their end and that we're waiting on a fix from @dcsan 

![screen shot 2015-11-02 at 9 19 48 am](https://cloud.githubusercontent.com/assets/6409227/10888848/479ac1ba-8143-11e5-97b7-3fb68e42c875.png)

**Comment by joepurdy** [comment]
I went ahead and monitored the logs for @purdybot since it also fails to talk to the api. Looks like this is related to the DNS migrations FCC did, see log:

```
GBot>  in| givepizza @dcsan
GBot> out|  > joepurdy gives pizza to @dcsan :metal: :rage1: :metal:
cant parse API response <html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.6 (Ubuntu)</center>
</body>
</html>
```

Any thoughts @dcsan or @BerkeleyTrue ?

**Comment by BerkeleyTrue** [comment]
try adding 'www'
