### ISSUE TITLE
implement menu system

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#36]
![image](https://cloud.githubusercontent.com/assets/514002/9023824/6e47ef74-3862-11e5-9e4e-9183f6bafd56.png)

when a user gets a list of responses back, typing a single number eg `0` should be enough to select the next item to retrieve.

(nice tip we could also use :one:  :two: ~ :nine: emoji for menu items)

**Comment by dcsan** [comment]
So i'm looking to change something in the GBot.js.parseInput() function it looks like.
dcsan 09:53
yes
so, we'd need some concept of state
the quick way would be that when you write out a find result
store those links in the GBots state
when someone then enters a single number, look it up in that state list
and show that entry
so that would get us a long way to what we need
BUT it's a bit of a hack, as when we have big scale, we'll get clashes if two people are searching at the same time in different rooms
dting 09:54
we would need a map of user to bot's last user?
err bot's last output for user?
dcsan 09:55
yeah, bots last user or bots by room.
saving state by room would be a good way to do it as later we'll have Room based conversations perhaps more than user based
eg if you and i are chatting to the same bot, in same room, we should be able to continue the conv, rather than have two convs... i think
that's a bit off in the future tho when i add conversation features
dting 09:56
but if two people are looking at different bf's for example, the later one would squash the earlier.
dcsan 09:56
yes, that's true.
i guess in the currrent usecase, overlapping BFs is a more likely scenario
dting 09:57
hmm also need some sort of timeout to cleanup that state.
dcsan 09:57
yes
but if its tied to user, its not too big a deal
so i'd suggest to go in steps, and get the functionality working
then go back and add things like splitting per user / room
since that's a bit complex working with the current GitterHelper API
or maybe not.
i think i added a room id to the input param that every botcommand gets
dting 10:00
okay i'll give it a shot. Haven't looked too deeply at the code yet but this should give me an chance to make myself more familiar.
dcsan 10:00
yep
so you'd setup the state at the end of the find command, that part should be easy
https://github.com/dcsan/gitterbot/blob/master/nap/lib/bot/BotCommands.js#L230-L241
but responding to individual/single characters
probably have to add a new type to the inputParser
https://github.com/dcsan/gitterbot/blob/master/nap/lib/bot/GBot.js#L122-L132
eg check if input.text is a single number
then what you could do is create a new command called "menuItem" and give it the params of whatever the text was, then call that command

**Comment by oab00** [comment]
oh my god!
I'm sorry I didn't mention that I was working on this one.. was just playing around and thankfully got it working to some extent.
all that conversation would've helped in the implementation maybe, but oh well.

**Comment by dcsan** [comment]
@oab00 no problem! It's great to see someone take this and work on it, its a kind of core feature!

hey I merged in your changes but it doesn't seem to be working for me locally.
it's in master as of commit   
e55db514bee5930943489d1f0ce65eb2d60a13f5

did i miss a merge, or did something else conflict? can you check again locally?

![image](https://cloud.githubusercontent.com/assets/514002/9185419/8d6cd670-3f70-11e5-90c6-6ceac4acbc59.png)

**Comment by dcsan** [comment]
as we chatted you might wanna parseInt the values getting entered by the user, as relying on numbers as named keys in a hashmap (object) is a bit risky!

**Comment by dcsan** [comment]
I think this is done? closing thanks @oab00 !
