### ISSUE TITLE
fix links to MDN content

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#45]
![image](https://cloud.githubusercontent.com/assets/514002/9025669/268f5ea4-38c3-11e5-97ed-6376fdf492c8.png)

there are some methods in the main freecodecamp repo to convert the links in the content to actual MDN URLs.

**Comment by dcsan** [comment]
@benmcmahon100 if you were able to take this one?

@BerkeleyTrue showed me a file in the main repo that converts the MDN function names into URLs.

**Comment by benmcmahon100** [comment]
@dcsan Here's the file https://github.com/FreeCodeCamp/freecodecamp/blob/staging/server/utils/index.js how do you want it implemented?

**Comment by dcsan** [comment]
I have a method in bonfires.js which is just pulling the data stored in the main json seed file - so the links are actually broken right now.
just need to copy/paste the 

```
    getLinks: function (bonfire) {
        // FIXME - change to actual links see
        // https://github.com/dcsan/gitterbot/issues/45
        var output = "links: \n";
        output += Utils.makeUrlList(bonfire.MDNlinks, 'mdn');
        return output;
    },
```

bringthis in from FCC code base, and add and make sure preloaded any other files that it needs to do the lookup. there's a `Bonfires.load()` fn near the top to add that to.


```
  getMDNLinks: function(links) {
    if (!links) {
      return [];
    }
    // takes in an array of links, which are strings

    // for each key value, push the corresponding link
    // from the MDNlinks object into a new array
    return links.map(function(value) {
      return MDNlinks[value];
    });
  }
```
