### ISSUE TITLE
unknown users has a %s in the error message

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#66]
![image](https://cloud.githubusercontent.com/assets/514002/9054025/b1a2c412-3a31-11e5-96f2-6cfba9e07680.png)

looks like string interpolate isn't firing, looks buggy...

i could suppress the message but i like to print them for now

**Comment by BerkeleyTrue** [comment]
Looking into it

Best,

___________________________________

Berkeley Martinez


Web Consultant at http://r3dm.com

Email: Berkeley@r3dm.com

Phone: (415) 763-7217

____________________________________

**Comment by dcsan** [comment]
![image](https://cloud.githubusercontent.com/assets/514002/9054508/204993b4-3a37-11e5-9556-971df3b5e65a.png)

i made a custom error msg anyway see above image

**Comment by dcsan** [comment]
just 
```

        var cleanMessage = function(message) {
            //return message;
            if (message.match(/^FCC: no user/)) {
                message = "hmm, can't find that user on the beta site. wait til we release new version!"
            }
            message = "> :warning: " + message;
            return message;
        }

```

**Comment by BerkeleyTrue** [comment]
Fixed!
