### ISSUE TITLE
add a hint for when users type '''

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#71]
add a keyword to the RoomMessages for this and return a :bulb:  use backticks!

![image](https://cloud.githubusercontent.com/assets/514002/9075839/cca2f226-3ace-11e5-9566-f546a3901ccc.png)

**Comment by dcsan** [comment]
since this is a static message it can be added here:
https://github.com/dcsan/gitterbot/blob/master/nap/data/rooms/RoomMessages.js

**Comment by dcsan** [comment]
@kirah1314 

> I was looking at add a hint for when users type ''' #71 on git, should I add the ''' to SharedMessages ? What does chance: 1 do?

its the % of time that response will come out. otherwise the bot could get really annoying...
0.2 = 20% chance

```
    scanInput: function(input, room, chance) {
        if (Math.random() > chance) {
            return null;   // dont always reply
        }
```

**Comment by kirah1314** [comment]
Completed! I saved it to master branch. Did I miss any steps?
