### ISSUE TITLE
debug oAuth on web app

### ISSUE THREAD

**Issue by dcsan** [dcsan/gitterbot#75]
currently sign in oauth page is broken

![image](https://cloud.githubusercontent.com/assets/514002/9080619/49941acc-3b0a-11e5-8961-f8ad95fcd81d.png)

why?

**Comment by irinatag** [comment]
@dcsan I plugged in my credentials from gitter, and it's working for me now after some debugging. Maybe you have incorrect redirect_uri: is it http://localhost:7891/login/callback not localhost:7000 as per their demo app? 
![gitterbot_host_app](https://cloud.githubusercontent.com/assets/2681074/9186202/6fc74630-3f77-11e5-9b48-94f334764b20.png)

**Comment by dcsan** [comment]
yes, that was what it was, thanks!!!
